name: プッシュ時の自動テスト
run-name: Auto Test
on:
  push:
    branches: [ main ]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle Test
        run:
          ./gradlew test;